language: ruby
bundler_args: "--without development production --deployment"
env:
- CODECLIMATE_REPO_TOKEN=33f5c18ba545e92e2744e55d1f0689ec91cf6cb2bb2e30d98c0f5cbfefede757 PG_USER=postgres PG_DB=travis_ci_test SECRET_KEY_BASE=df55ce581687c876790adc5e98a0d3ba41905f772a6ed4dc3f8143e8997185d3f0a1332ef0bd03a599685da786ca129c9c26f6fc86bf4d39ee8fbaa90915f584 APP_HOST=travisci.joatu.com
addons:
  postgresql: '9.3'
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -U postgres -c "create extension postgis"
notifications:
  slack:
    secure: p6EaU4uR3ij6wS85B3HJOX6bH9IKbs9NCuPXfmulLigbRaLRPRtp0j7fZRaidjZvb/up5MMv6uJXJmjByrVL4FHY6NJVkNEY4LhRa/yKG50ld7JZEWvzkGHKXgAW4Sl/w++f5WQKhSX6M6PdOqWNg6cokpQizCUbUTKEmT20ohg=
