paths:
  jquery: 'jquery-1.10.2'
  bootstrap: 'bootstrap.min'
  underscore: 'lodash.underscore-2.4.1'
  backbone: 'backbone-1.1.0'
  chaplin: 'chaplin-1.0.0'
shim:
  'backbone':
    deps: ['underscore', 'jquery']
    exports: 'Backbone'
  'bootstrap':
    deps: ['jquery']
